# .NET MAUI Build Pipeline for Windows

trigger:
- '*'
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln' 
  mauiAppProject: 'ICS_Project.App/ICS_Project.App.csproj'
  buildConfiguration: 'Release'
  windowsTargetFramework: 'net8.0-windows10.0.19041.0'
  dotnetSdkVersion: '8.0.406' 

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetSdkVersion)'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'Restore .NET MAUI Workloads'
  inputs:
    command: 'custom'
    custom: 'workload'
    arguments: 'restore --source https://api.nuget.org/v3/index.json'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build MAUI App for Windows'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(mauiAppProject)'
    arguments: '--framework $(windowsTargetFramework) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/App.Windows -r win-x64 /p:WindowsPackageType=None /p:PublishProfile=win-$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Windows App Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/App.Windows'
    ArtifactName: 'maui-windows-app'
    publishLocation: 'Container'
  condition: succeededOrFailed()